services:
  rabbitmq:
    image: rabbitmq:management
    container_name: eventflowx_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eventflowx_mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin1234!"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Admin1234!' -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  consumer:
    build:
      context: .
      dockerfile: EventFlowX.Consumer/Dockerfile
    container_name: eventflowx_consumer
    depends_on:
      - rabbitmq
      - mssql
    environment:
      - DOTNET_ENVIRONMENT=Docker
      - INSTANCE_ID=worker-consumer

  host:
    build:
      context: .
      dockerfile: EventFlowX.Host/Dockerfile
    container_name: eventflowx_host
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - mssql
    environment:
      - DOTNET_ENVIRONMENT=Docker
      - INSTANCE_ID=worker-host

volumes:
  rabbitmq_data:
  mssql_data: