// <auto-generated />
using System;
using EventFlowX.Host.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventFlowX.Host.Migrations
{
    [DbContext(typeof(OutboxDbContext))]
    [Migration("20260406134224_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventFlowX.Shared.Models.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessingBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingBy");

                    b.HasIndex("Status");

                    b.ToTable("OutboxEvents", t =>
                        {
                            t.Property("EventType")
                                .HasColumnName("OutboxEvent_EventType");
                        });
                });

            modelBuilder.Entity("EventFlowX.Shared.Models.Pod", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InstanceId");

                    b.HasIndex("Status");

                    b.ToTable("Pods");
                });

            modelBuilder.Entity("EventFlowX.Shared.Models.OutboxEvent", b =>
                {
                    b.HasOne("EventFlowX.Shared.Models.Pod", "Pod")
                        .WithMany()
                        .HasForeignKey("ProcessingBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("EventFlowX.Shared.Models.EventMessage", "Data", b1 =>
                        {
                            b1.Property<Guid>("OutboxEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EventId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("EventId");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("EventType");

                            b1.Property<DateTime>("OccurredAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("OccurredAt");

                            b1.Property<string>("Payload")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Payload");

                            b1.HasKey("OutboxEventId");

                            b1.ToTable("OutboxEvents");

                            b1.WithOwner()
                                .HasForeignKey("OutboxEventId");
                        });

                    b.Navigation("Data")
                        .IsRequired();

                    b.Navigation("Pod");
                });
#pragma warning restore 612, 618
        }
    }
}
