// <auto-generated />
using System;
using EventFlowX.Host.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventFlowX.Host.Migrations
{
    [DbContext(typeof(OutboxDbContext))]
    [Migration("20260405134700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("EventFlowX.Shared.Models.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingBy");

                    b.HasIndex("Status");

                    b.ToTable("OutboxEvents");
                });

            modelBuilder.Entity("EventFlowX.Shared.Models.Pod", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("InstanceId");

                    b.HasIndex("Status");

                    b.ToTable("Pods");
                });

            modelBuilder.Entity("EventFlowX.Shared.Models.OutboxEvent", b =>
                {
                    b.HasOne("EventFlowX.Shared.Models.Pod", "Pod")
                        .WithMany()
                        .HasForeignKey("ProcessingBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Pod");
                });
#pragma warning restore 612, 618
        }
    }
}
